############################
# --- Required options --- #
############################

# Name of website
title: null

# Your name to show in the footer
author: EvanHsieh0415


###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  Personal Page: "personal-page/"
  Storage: "storage/"
  Useful Links: "useful links/"


################
# --- Logo --- #
################

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: https://avatars.githubusercontent.com/u/74277414

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
title-img: https://avatars.githubusercontent.com/u/74277414


#####################################
# --- Footer social media links --- #
#####################################

# Select the social network links that you want to show in the footer.
# You can change the order that they show up on the page by changing the order here.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  rss: true  # remove this line if you don't want to show an RSS link at the bottom
  github: EvanHsieh0415
  twitter: YTMango1
  # patreon: DeanAttali
  youtube: "@YTMango"
  discord: "invite/SCAfRyAVnR"


###########################
# --- General options --- #
###########################

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true


name: EvanHsieh's Personal Github Pages
